### ISSUE TITLE
WSL2 support?

### ISSUE THREAD

**Issue by ziporah** [clayfreeman/gpu-passthrough#2]
Hello, great tutorial!
Did you by any chance validate if your system supports wsl2 ?
I've been trying to get it running on my virtual win10 with gpu passtrough, but I don't seem to be able to enable hyper-v.
I would love to be able to use the new docker client in windows with wsl2, but just can't seem to get my head around it.
The kvm settings are correct. I can run virtualbox, even tried ubuntu livecd with kvm enabled and run ubuntu in a vm in the live environment. I just don't seem to find a way to make hyper-v and my GPU work. 
As soon as hyper-v get enabled during boottime, my RX580 gets the Error 43 code again and on top of that, hyper-v isn't even working, so no wsl2 either

**Comment by clayfreeman** [comment]
Thanks for your interest in this tutorial!

Have you tried the steps on this page to enable nested virtualization support? https://www.linux-kvm.org/page/Nested_Guests#How_to_run

What CPU model are you using for the Windows guest?

**Comment by ziporah** [comment]
Hello, I'm able to run full nested kvm with ubuntu L0, ubuntu L1 and ubuntu L2, with GPU passthrough, cpu model is CPU passthrough, only option enabled is 
```
<feature policy='disable' name='hypervisor'/>
```
But if I try windows 10, with the same virtual machine, it installs fine, I'm able to get the gpu drivers on there, but as soon as it starts enabling hyperv, the machine is lost. No more gpu, random cpu locking at 100% for all cores, and so on.
It's even so bad that windows updates is causing the machine to enter this state.
I've reinstalled several times, trying to find out what is going on. Disabled windows driver update with group policy, ...
only option that seems to work is disabling hyper-v, which makes my GPU functional again, but disables wsl2 functionality.
I already discovered I need this to work:
```
bcdedit /set hypervisorlaunchtype off
```
I manage to get hyperv working with spice server with this settings:
```
bcdedit /set hypervisorlaunchtype auto
bcdedit /set hypervisorschedulertype Classic
```
These settings allow wsl 2 to create the hyper-v machines with multiple cores and hyperthreading

I have a Intel 8750 cpu,
the relevant kvm lines:
```
  7   <iothreads>1</iothreads>
  8   <cputune>
  9   | <vcpupin vcpu='0' cpuset='2'/>
 10   | <vcpupin vcpu='1' cpuset='8'/>
 11   | <vcpupin vcpu='2' cpuset='3'/>
 12   | <vcpupin vcpu='3' cpuset='9'/>
 13   | <vcpupin vcpu='4' cpuset='4'/>
 14   | <vcpupin vcpu='5' cpuset='10'/>
 15   | <vcpupin vcpu='6' cpuset='5'/>
 16   | <vcpupin vcpu='7' cpuset='11'/>
 17   | <emulatorpin cpuset='0,6'/>
 18   | <iothreadpin iothread='1' cpuset='0,6'/>
 19   </cputune>
 24   | <type arch='x86_64' machine='pc-i440fx-2.11'>hvm</type>
 25   | <loader readonly='yes' type='pflash'>/usr/share/OVMF/OVMF_CODE.fd</loader>
 26   | <nvram>/var/lib/libvirt/qemu/nvram/ubuntu_VARS.fd</nvram>
 32   | <hyperv>
 33   | ¦ <relaxed state='on'/>
 34   | ¦ <vapic state='on'/>
 35   | ¦ <spinlocks state='on' retries='8191'/>
 36   | ¦ <vpindex state='on'/>
 37   | ¦ <runtime state='on'/>
 38   | ¦ <synic state='on'/>
 39   | ¦ <stimer state='on'/>
 40   | ¦ <reset state='on'/>
 41   | ¦ <vendor_id state='on' value='1234567890ab'/>
 42   | ¦ <frequencies state='on'/>
 43   | </hyperv>
 44   | <kvm>
 45   | ¦ <hidden state='on'/>
 46   | </kvm>
 47   | <vmport state='off'/>
 48   | <ioapic driver='kvm'/>
 49   </features>
 50   <cpu mode='host-passthrough' check='none'>
 51   | <topology sockets='1' cores='4' threads='2'/>
 52   | <feature policy='require' name='vmx'/>
 53   | <feature policy='disable' name='hypervisor'/>
 54   </cpu>
 54   </cpu>
 55   <clock offset='localtime'>
 56   | <timer name='rtc' tickpolicy='catchup'/>
 57   | <timer name='pit' tickpolicy='delay'/>
 58   | <timer name='hpet' present='yes'/>
 59   | <timer name='hypervclock' present='yes'/>
 60   </clock>
```
I've tried turning on/of settings removing the hypervisor cpuid bit, but none seems to fix the gpu error 43 code and keep the windows stable

**Comment by clayfreeman** [comment]
I've confirmed that the issue appears to be related to nested Hyper-V virtualization in KVM. I was able to replicate everything that you described. I'll be taking an additional look at this in a few days, hopefully with a plan in mind.

**Comment by ziporah** [comment]
I'm in the process of upgrading my base system to ubuntu 20.04 to get the latest libvirt and qemu. I'll report back after I manage to test again. The above tests were all run on default installation with ubuntu 18.04

**Comment by ziporah** [comment]
Hello, just wanted to ping back, I seem to have found a working solution.
```
<domain type='kvm' id='6'>
  <name>win10-q35</name>
  <memory unit='KiB'>12562432</memory>
  <currentMemory unit='KiB'>12562432</currentMemory>
  <memoryBacking>
    <hugepages/>
  </memoryBacking>
  <vcpu placement='static'>8</vcpu>
  <iothreads>1</iothreads>
  <cputune>
    <vcpupin vcpu='0' cpuset='2'/>
    <vcpupin vcpu='1' cpuset='8'/>
    <vcpupin vcpu='2' cpuset='3'/>
    <vcpupin vcpu='3' cpuset='9'/>
    <vcpupin vcpu='4' cpuset='4'/>
    <vcpupin vcpu='5' cpuset='10'/>
    <vcpupin vcpu='6' cpuset='5'/>
    <vcpupin vcpu='7' cpuset='11'/>
    <emulatorpin cpuset='0,6'/>
    <iothreadpin iothread='1' cpuset='0,6'/>
  </cputune>
  <resource>
    <partition>/machine</partition>
  </resource>
  <os>
    <type arch='x86_64' machine='pc-q35-4.2'>hvm</type>
    <loader readonly='yes' type='pflash'>/usr/share/OVMF/OVMF_CODE.fd</loader>
    <nvram>/var/lib/libvirt/qemu/nvram/win10_VARS.fd</nvram>
    <bootmenu enable='no'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv>
      <relaxed state='on'/>
      <vapic state='on'/>
      <spinlocks state='on' retries='8191'/>
      <vpindex state='on'/>
      <runtime state='on'/>
      <synic state='on'/>
      <stimer state='on'/>
      <reset state='on'/>
      <vendor_id state='on' value='1234567890ab'/>
      <frequencies state='on'/>
    </hyperv>
    <kvm>
      <hidden state='on'/>
    </kvm>
    <vmport state='off'/>
    <ioapic driver='kvm'/>
  </features>
  <cpu mode='host-passthrough' check='none'>
    <topology sockets='1' cores='4' threads='2'/>
    <feature policy='require' name='vmx'/>
    <feature policy='disable' name='hypervisor'/>
    <feature policy='require' name='stibp'/>
  </cpu>
  <clock offset='localtime'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
    <timer name='hypervclock' present='yes'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>

```
This with ubuntu 20.04, installed qemu and libvirt from the repository, added the ovmf package as well
These are the commandline options:
```
BOOT_IMAGE=/vmlinuz-5.4.0-42-generic root=/dev/mapper/rootvg-rootlv ro cgroup_enable=memory swapaccount=1 intel_iommu=on iommu=pt radeon.modeset=0 nouveau.modeset=1 fbcon=map:1 modprobe.blacklist=3w_9xxx vfio-pci.ids=1002:679a,1002:6798,1002:aaa0,1002:67df,1002:aaf0 vfio-pci.disable_idle_d3=1 pci=noaer modprobe.blacklist=amdgpu amdgpu.modeset=0 video=vesafb:off,efifb:off
```
It does still manifest the Error43 code, but I managed to solve this using a startup/shutdown script with devcon disable/enabling the hardware [https://forum.level1techs.com/t/linux-host-windows-guest-gpu-passthrough-reinitialization-fix/121097?source_topic_id=121737](link)
After fixing this and using the above configuration, I managed to install wsl2 and boot the hyperV vm with a quad core/4GB of ram.
I've changed the hyperv scheduler type to this:
```
hypervisorlaunchtype    Auto
hypervisorschedulertype Classic
```
Not sure this is really required, Root scheduler might work as well, the default will not work I believe as my processor isn't capable of passing the security stuff with nested virtualization. Newer processors might work, but I don't have these at my disposal.
Overall, the machine works, and I can play games. It might need some more tweaking to become a bit more snappy, but for now I'm happy with the result.

**Comment by clayfreeman** [comment]
Excellent news! Thanks for the update.

I personally never encountered a Code 43 issue with my graphics card, and the only difference on my end was the hypervisor scheduler type, so I imagine that setting that to "Classic" is the fix for nested Hyper-V virtualization in KVM.
