### ISSUE TITLE
when comand line "nvidia-smi“ in linux terminal，no devices were found  in gpu-passthrough for GPU T4

### ISSUE THREAD

**Issue by lishuwei0424** [clayfreeman/gpu-passthrough#4]
hello,I make gpu-passthroug with  GPU Tesla T4 on  kvm。host device is redhat,but virtual machine is centos.
when comand line "nvidia-smi“ in linux terminal，no devices were found,as follow;

then vim  /var/log/message，find as  follows:
![image](https://user-images.githubusercontent.com/42164855/92296743-36039e00-ef6a-11ea-91e1-23d03c4c9d44.png,
can you give some suggestion thank you

**Comment by clayfreeman** [comment]
Please try [setting the hypervisor CPU feature to disabled](https://github.com/clayfreeman/gpu-passthrough/blob/master/resources/example-domain.xml#L23) according to [the instructions in the tutorial](https://clayfreeman.github.io/gpu-passthrough/#hiding-the-virtualization-environment). This is from my Ubuntu VM:

```
$ nvidia-smi 
Sat Sep  5 16:49:25 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
| 21%   55C    P5    39W / 250W |   1649MiB / 11019MiB |     39%      Default |
+-------------------------------+----------------------+----------------------+
```

You should also verify that you're using NVIDIA's proprietary drivers within the VM. In addition, you may need additional packages for CUDA support.

**Comment by lishuwei0424** [comment]
> Please try [setting the hypervisor CPU feature to disabled](https://github.com/clayfreeman/gpu-passthrough/blob/master/resources/example-domain.xml#L23) according to [the instructions in the tutorial](https://clayfreeman.github.io/gpu-passthrough/#hiding-the-virtualization-environment). This is from my Ubuntu VM:
> 
> ```
> $ nvidia-smi 
> Sat Sep  5 16:49:25 2020       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
> | 21%   55C    P5    39W / 250W |   1649MiB / 11019MiB |     39%      Default |
> +-------------------------------+----------------------+----------------------+
> ```
> 
> You should also verify that you're using NVIDIA's proprietary drivers within the VM. In addition, you may need additional packages for CUDA support.

thanks you for  reply!.I test  for mainboard x10 for  intel,other than Hygon, finally it works well .I doubt mainboard has  influence on  NVIDIA driver.

**Comment by clayfreeman** [comment]
If you have any further questions, feel free to submit another issue. Thanks!
