### ISSUE TITLE
network cards are not visible/accessible after enabling passthrough (intel_iommu=on)

### ISSUE THREAD

**Issue by nicoMagics** [clayfreeman/gpu-passthrough#5]
Hey, 

I'm trying to execute the tutorial of the gpu-passthrough, sadly i get stuck already at step 1)
After I enable the gpu-passthrough (kernel option intel-iommu=on) and reboot the network interfaces that where configured before are not accessible anymore.

Is this normal behavior? 
From what I did read here or on the RHV doc it doesn't sound to happen in this way.
(RHV: https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html/setting_up_an_nvidia_gpu_for_a_virtual_machine_in_red_hat_virtualization/proc_nvidia_gpu_passthrough_nvidia_gpu_passthrough#Detaching_the_GPU_device_from_the_host_nvidia_gpu_passthrough )

I did also try to add the option "iommu=pt", no difference here.
Do I need to enable the unsafe interupt support or is this totally not related?

Currently I'm using the next harwarde:

Supermicro 4029GP-TRT 5U Server
2 x Intel xeon Gold 5217
12 x Certified 16GB DDR4 2666MHZ ECC REG
1 x Samsung 480GB PM883
1 x Nvidia RTX 2080Ti OEM card

Any tips?

Already many thanks! 

Br, Nico

**Comment by clayfreeman** [comment]
Can you confirm whether the device still appears in `lspci -nnv`? If so, what modules / drivers are listed? Does this list change before/after adding the command-line argument to the kernel?
