### ISSUE TITLE
Where can i find the script to load my vGPU mdev configuration on boot ?

### ISSUE THREAD

**Issue by S4nfs** [clayfreeman/gpu-passthrough#7]
Rebooting the host removes hostdev configuration, How do i automate this using modules ?

error: failed to read '/sys/bus/mdev/devices/301b7a7e-6704-4393-aa72-0255ccf3fe80/mdev_type/device_api': No such file or directory

**Comment by clayfreeman** [comment]
I've never used a mediated device before, so you're on your own here. Sorry!
